**Importing Libraries**

In [7]:
# Importing Libraries
import numpy as np

In [8]:
# Declaring 1D Array
Array1 = np.array([1,2,3,4])
print(Array1)

[1 2 3 4]


In [9]:
# Declaring 2D Array
Array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(Array2)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# Declaring 3D Array
Array3 = np.array([[[1,2,3,4],[1,2,3,4]],
                   [[5,6,7,8],[5,6,7,8]],
                   [[9,10,11,12],[9,10,11,12]]])
print(Array3)

[[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 9 10 11 12]]]


In [ ]:
np.array?

In [11]:
Array1.dtype

dtype('int32')

In [12]:
Array4 = np.array([1,2,3,4,5], dtype='float64')


In [13]:
Array4.shape

(5,)

In [15]:
Array4.ndim

1

In [16]:
Array4.size

5

In [ ]:
Array4.itemsize