**Importing Libraries**

In [7]:
import numpy as np

**Creating numpy arrays**

In [8]:
# Declaring 1D Array
Array1 = np.array([1,2,3,4])
print(Array1)

[1 2 3 4]


In [41]:
# Declaring 2D Array
Array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Declaring 3D Array
Array3 = np.array([[[1,2,3,4],[1,2,3,4]],
                   [[5,6,7,8],[5,6,7,8]],
                   [[9,10,11,12],[9,10,11,12]]])
print(Array3)

[[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 9 10 11 12]]]


In [ ]:
np.array?

**Basic Numpy Attributes**

In [26]:
print("Datatype -",Array1.dtype)
print("Matrix Shape -",Array1.shape)
print("Dimension -",Array1.ndim)
print("size -",Array1.size)
print("item size in Bytes",Array1.itemsize)
print("array size in Bytes",Array1.nbytes)

Datatype - int32
Matrix Shape - (4,)
Dimension - 1
size - 4
item size in Bytes 4
array size in Bytes 16


In [32]:
Array4 = np.array([1,2,3,4,5], dtype='float64') # for every dtype size nd memory changes according to it
print("Datatype -",Array4.dtype)

Array4 = np.array([1,2,3,4,5,'sas']) # String dtype
print("Datatype -",Array4.dtype)

Datatype - float64
Datatype - <U11


In [36]:
# Convert to Multidimensional array
Array5 = np.array([1,2,3,4,5], ndmin=3)
Array5

array([[[1, 2, 3, 4, 5]]])

In [48]:
print(Array2[0]) # -> outer array
print(Array2[1]) # -> next layer array
print(Array2[2]) # -> next layer array -> here innermost

print(Array3[0][0])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[1 2 3 4]
